### ISSUE TITLE
 Request for Documentation and Containerization of Bio::EnsEMBL::XS Module for VEP

### ISSUE THREAD

**Issue by JoshuaSWIBI** [Ensembl/ensembl-xs#14]
Hi,

I am working on annotating large datasets, specifically WGS VCF files, using VEP. I came across the `Bio::EnsEMBL::XS` module mentioned in the VEP documentation and decided to install it as per the instructions. However, there are no clear guidelines on how to effectively use this module to improve VEP performance.

Details: 

Environment:
  - Azure VM with 32 vCPUs and 64GB RAM
  - VEP installed and running in a Docker container

Issues:

1. Lack of Documentation:
   - There are no detailed instructions on how to use the `Bio::EnsEMBL::XS` module with VEP.
   - It is unclear how this module optimizes VEP and what specific steps need to be taken to leverage its capabilities.

2. Containerization:
   - I would like to know if it is possible to containerize the `Bio::EnsEMBL::XS` module and use it within the VEP Docker container.
   - If yes, I need guidance on the steps to achieve this.

Request:

Documentation:
  - Please provide detailed documentation on how to use the `Bio::EnsEMBL::XS` module with VEP, including examples and best practices.
  - Information on how this module improves VEP performance would be highly appreciated.

Containerization:
  - If possible, provide instructions or a Dockerfile example on how to integrate the `Bio::EnsEMBL::XS` module into the VEP Docker container.
  - Any additional configurations or dependencies required for the module to function optimally within the container.

Thank you for your support. Any help or pointers to relevant documentation would be a great favor.

Best regards,
Joshua Ravi

**Comment by sgiorgetti** [comment]
Hello @JoshuaSWIBI ,

Thanks for your question.
As mentioned by @likhitha-surapaneni in VEP repo https://github.com/Ensembl/ensembl-vep/issues/1722, `ensembl-xs` should be included in VEP image by default.
From your/user perspective, the use of XS should be sort-of transparent and in theory requiring at most switching a flag. In practice for the VEP, there's nothing to do on your end as per my understanding.
Asked the Variation colleagues to confirm.

 Hope it helps

**Comment by sgiorgetti** [comment]
Confirmed. The `ensembl-variation` code has some logic to use `ensembl-xs` if present or default to pure Perl otherwise.

**Comment by JoshuaSWIBI** [comment]
Thanks @sgiorgetti
